version: '2'
services:
  lidarr:
    container_name: lidarr
    image: volikon/lidarr
    environment:
      - TZ=<timezone>
    ports:
      - "8686:8686"
    volumes:
      - ./config:/config
      - ./music:/music
